/**
 * AMC CSV Parser
 * Parse exam-answers.csv (or answers.csv) generated by AMC
 * to extract answer key (which option is correct for each question)
 *
 * AMC CSV format (auto-generated):
 *   # AMC Answers File
 *   # Question;Copies;Student;Origin;Date;Sheet;Copie;Answers
 *   1;"";"";"q1";"";"";"";"A"
 *   2;"";"";"q2";"";"";"";"B"
 *   ...
 *
 * For combined sources, each row has:
 *   Question number; (empty); (empty); original question ID; (date); (sheet); (copy); correct answer letter(s)
 *
 * EXPORTS BOTH:
 *   - Module functions (for new pipeline: examPaper.service.js)
 *   - Class with parse() method (for old pipeline: amc.service.js)
 */

const ENCODING_OPTIONS = ['utf8', 'latin1', 'ascii'];

/**
 * Parse AMC answers CSV text
 * @param {string} content - raw CSV content
 * @returns {Object} parsed answer data
 */
function parseAmcCsv(content) {
  if (!content || typeof content !== 'string') {
    return { answers: {}, meta: {} };
  }

  const answers = {};
  let meta = { totalQuestions: 0, source: 'amc-csv' };
  const lines = content.split('\n');

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      if (line.startsWith('#AMC') || line.startsWith('# AMC')) {
        meta.amcVersion = line.replace(/^#/, '').trim();
      }
      continue;
    }

    // Split by semicolon (AMC CSV uses semicolons)
    // But we need to handle quoted fields with semicolons inside
    const fields = splitCsvLine(line, ';');

    if (fields.length < 8) continue;

    const [qNumStr, , , origId, , , , answersStr] = fields;

    const qNum = parseInt(qNumStr, 10);
    if (isNaN(qNum) || qNum <= 0) continue;

    // Parse answer letters from answersStr (e.g., "A", "BC", "A;D", etc.)
    const letters = (answersStr || '')
      .replace(/["']/g, '')
      .split(';')
      .map(s => s.trim().toUpperCase())
      .filter(Boolean);

    answers[qNum] = {
      questionNum: qNum,
      correctOptions: letters,
      originalId: origId || `q${qNum}`,
    };

    meta.totalQuestions = Math.max(meta.totalQuestions, qNum);
  }

  return { answers, meta };
}

/**
 * Smart CSV line split that respects quoted fields
 * @param {string} line
 * @param {string} delimiter
 * @returns {string[]}
 */
function splitCsvLine(line, delimiter = ';') {
  const result = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      inQuotes = !inQuotes;
    } else if (ch === delimiter && !inQuotes) {
      result.push(current.trim());
      current = '';
    } else {
      current += ch;
    }
  }
  result.push(current.trim());

  return result;
}

/**
 * Read AMC CSV from file, trying multiple encodings
 * @param {string} filePath
 * @param {fs} fsModule
 * @returns {Promise<string>} raw content
 */
async function readCsvFile(filePath, fsModule = require('fs')) {
  const fs = fsModule;
  if (!fs.existsSync(filePath)) {
    throw new Error(`CSV file not found: ${filePath}`);
  }

  // Try UTF-8 first, then fallback
  for (const enc of ENCODING_OPTIONS) {
    try {
      const content = fs.readFileSync(filePath, enc);
      if (content && content.length > 0) return content;
    } catch {
      // try next encoding
    }
  }

  throw new Error(`Failed to read CSV with any encoding: ${filePath}`);
}

/**
 * Read and parse AMC CSV from file
 * @param {string} filePath
 * @param {fs} fsModule
 * @returns {Promise<Object>} parsed answer data
 */
async function readAndParseCsv(filePath, fsModule = require('fs')) {
  const content = await readCsvFile(filePath, fsModule);
  return parseAmcCsv(content);
}

/**
 * Build answer key mapping from parsed CSV data
 * @param {Object} csvData - result of parseAmcCsv()
 * @param {string} versionCode - e.g. '101'
 * @returns {Map<string, string>} position -> correct option letter
 */
function buildAnswerKey(csvData, versionCode = '') {
  const key = new Map();
  for (const [qNumStr, data] of Object.entries(csvData.answers)) {
    const letter = (data.correctOptions[0] || '').toUpperCase();
    if (letter) {
      key.set(qNumStr, letter);
    }
  }
  return key;
}

/**
 * Convert Map answer key to plain object
 * @param {Map|string|Object} answerKey
 * @returns {Object}
 */
function answerKeyToObject(answerKey) {
  if (!answerKey) return {};
  if (typeof answerKey === 'object' && !(answerKey instanceof Map)) return answerKey;
  if (answerKey instanceof Map) return Object.fromEntries(answerKey);
  // If string (JSON), parse
  try { return JSON.parse(answerKey); } catch { return {}; }
}

module.exports = {
  parseAmcCsv,
  readCsvFile,
  readAndParseCsv,
  buildAnswerKey,
  answerKeyToObject,
  /**
   * BACKWARD-COMPAT CLASS
   * Used by amc.service.js (old pipeline)
   * New code should use the module functions directly.
   */
  CsvParser: class CsvParser {
    parse(content) {
      return parseAmcCsv(content);
    }
    async readAndParse(filePath, fs) {
      return readAndParseCsv(filePath, fs);
    }
  },
};
