/**
 * AMC Calage Parser
 * Parse .calage.xy file generated by AMC to extract bubble coordinates
 *
 * Format .calage.xy (AMC 1.x, v2023+):
 *   \tracepos{page:label}{x}{y}{shape}
 *   \boxchar{page:label}{char}
 *
 * Each bubble has 2 tracepos entries (top-left and bottom-right corners):
 *   \tracepos{1/1:case:q1:1,4}{x1_sp}{y1_sp}{square}  -- top-left
 *   \tracepos{1/1:case:q1:1,4}{x2_sp}{y2_sp}{square}  -- bottom-right
 *
 * We pair them to calculate actual bubble width/height.
 *
 * Examples:
 *   Student ID: chiffre:1,5 = digit 1, value 5
 *   Version: case:ver:1,1 = version digit 1, value 1
 *   Question: case:q1:1,4 = question q1, option 4 (D)
 *
 * Coordinate system in AMC:
 *   - Origin is TOP-LEFT (already image coordinates!)
 *   - Units are sp (scaled points): 1pt = 65536sp
 *   - PDF page height: 842pt for A4
 */

const SCALED_POINTS_PER_PT = 65536;
const PDF_PT_PER_INCH = 72;
const A4_HEIGHT_PT = 842;

/**
 * Convert sp (scaled points) to PDF points
 */
function spToPt(sp) {
  return parseFloat(sp) / SCALED_POINTS_PER_PT;
}

/**
 * Parse raw .calage.xy text content
 * @param {string} content - raw file content
 * @returns {Object} parsed bubble data
 */
function parseCalage(content) {
  if (!content || typeof content !== 'string') {
    return { bubbles: [], questions: {}, meta: {}, studentId: null, versionCode: null };
  }

  const bubbles = [];
  const questions = {};
  const studentIdBubbles = {};
  const versionCodeBubbles = {};
  const lines = content.split('\n');
  let header = null;
  let pageHeightPt = A4_HEIGHT_PT; // Default A4

  // First pass: collect all tracepos entries grouped by label
  // Each bubble has 2 entries (top-left and bottom-right corners)
  const traceposByLabel = {};

  for (const rawLine of lines) {
    const line = rawLine.trim();

    // Skip empty lines
    if (!line) continue;

    // Capture header info
    if (line.startsWith('\\version{')) {
      header = line;
      continue;
    }

    // Parse page dimensions
    // \page{0/1/60}{597.50787pt}{845.04684pt}{...}
    const pageMatch = line.match(/^\\page\{[^}]+\}\{[^}]+\}\{([^}]+)pt\}/);
    if (pageMatch) {
      pageHeightPt = parseFloat(pageMatch[1]) || A4_HEIGHT_PT;
      continue;
    }

    // Parse \tracepos{page:label}{x}{y}{shape}
    const traceMatch = line.match(/^\\tracepos\{([^}]+)\}\{([^}]+)\}\{([^}]+)\}\{([^}]+)\}/);
    if (!traceMatch) continue;

    const [, label, xSp, ySp, shape] = traceMatch;

    // Skip position markers (positionHG, positionHD, etc.)
    if (label.includes('position')) continue;

    // Convert sp to PDF points
    const xPt = spToPt(xSp);
    const yPt = spToPt(ySp);

    // Store by label for pairing
    if (!traceposByLabel[label]) {
      traceposByLabel[label] = [];
    }
    traceposByLabel[label].push({ x: xPt, y: yPt, shape });
  }

  // Second pass: process paired tracepos entries
  for (const [label, points] of Object.entries(traceposByLabel)) {
    if (points.length < 2) continue;

    // Remove page prefix (e.g., "0/1:") to get the actual label
    // Format varies:
    //   - "case:q1[1]:10,1" = question q1 (version 1), position 10, value 1 (A)
    //   - "case:student[7]:1,1" = student ID digit 7, position 1, value 1
    //   - "case:ver1[1]:8,1" = version 1 digit 1, position 8, value 1
    //   - "chiffre:1,5" = student ID (legacy format)
    const actualLabel = label.replace(/^\d+\/\d+:/, '');

    // Sort points by x+y to identify corners (top-left vs bottom-right)
    const sorted = [...points].sort((a, b) => a.x + a.y - (b.x + b.y));
    const topLeft = sorted[0];
    const bottomRight = sorted[sorted.length - 1];
    const shape = topLeft.shape;

    // Calculate actual bubble dimensions
    const w = Math.abs(bottomRight.x - topLeft.x);
    const h = Math.abs(bottomRight.y - topLeft.y);

    if (actualLabel.startsWith('case:')) {
      // New format: case:NAME[INDEX]:POSITION,VALUE
      // Examples: case:q1[1]:10,1, case:student[7]:1,1, case:ver1[1]:8,1
      // Also handles: case:ver1:1,1 (no brackets)
      const caseMatch = actualLabel.match(/^case:([^:[]+)(?:\[(\d+)\])?:(\d+),(\d+)$/);
      if (caseMatch) {
        const [, name, indexStr, posStr, valueStr] = caseMatch;
        const position = parseInt(posStr, 10);
        const value = parseInt(valueStr, 10);

        // Student ID field - supports both "student" and "chiffre" names
        if (name === 'student' || name.match(/^chiffre\d*$/)) {
          const digit = parseInt(indexStr || '1', 10);
          if (!studentIdBubbles[digit]) studentIdBubbles[digit] = {};
          studentIdBubbles[digit][value] = {
            x: topLeft.x,
            y: topLeft.y,
            w: Math.round(w),
            h: Math.round(h),
            digit,
            value,
          };
          continue;
        }

        // Version code field - supports multiple formats:
        // - "ver" with [INDEX] bracket → digit = INDEX
        // - "ver1", "ver2" (digit number is the number after "ver")
        // - "ver" (no number) → use position as digit
        const verWithBracketMatch = name.match(/^ver\[(\d+)\]$/);
        const verWithDigitMatch = name.match(/^ver(\d+)$/);

        if (verWithBracketMatch || verWithDigitMatch || name === 'ver') {
          let verDigit;
          if (verWithBracketMatch) {
            // Format: ver[1], ver[2] → digit from bracket
            verDigit = parseInt(verWithBracketMatch[1], 10);
          } else if (verWithDigitMatch && verWithDigitMatch[1]) {
            // Format: ver1, ver2 → digit from number after "ver"
            verDigit = parseInt(verWithDigitMatch[1], 10);
          } else if (name === 'ver' && indexStr) {
            // Format: ver[2] → digit from bracket index (already parsed as indexStr)
            verDigit = parseInt(indexStr, 10);
          } else {
            // Format: ver (no number) → use position as digit
            verDigit = position;
          }
          if (!versionCodeBubbles[verDigit]) versionCodeBubbles[verDigit] = {};
          versionCodeBubbles[verDigit][value] = {
            x: topLeft.x,
            y: topLeft.y, // AMC already uses image coords (top-left origin)
            w: Math.round(w),
            h: Math.round(h),
            digit: verDigit,
            value,
          };
          continue;
        }

        // Question bubble: q1, q2, etc.
        const qMatch = name.match(/^q(\d+)$/);
        if (qMatch) {
          const qNum = parseInt(qMatch[1], 10);

          // Option letter: value 1=A, 2=B, 3=C, 4=D
          const optionLetter = ['A', 'B', 'C', 'D', 'E', 'F'][value - 1] || `opt${value}`;

          const bubble = {
            id: `${qNum}:${optionLetter}`,
            questionNum: qNum,
            digit: position,
            value,
            optionLetter,
            x: topLeft.x,
            y: topLeft.y, // AMC already uses image coords (top-left origin)
            w: Math.round(w),
            h: Math.round(h),
            type: 'box',
            shape,
          };

          bubbles.push(bubble);

          if (!questions[qNum]) {
            questions[qNum] = { questionNum: qNum, slots: {} };
          }

          // Only store bubble with smallest x (leftmost) for this option
          // AMC may have multiple bubbles per option (at different positions)
          // We want the FIRST bubble (leftmost in the row)
          const existing = questions[qNum].slots[optionLetter];
          if (!existing || bubble.x < existing.x) {
            questions[qNum].slots[optionLetter] = bubble;
          }
        }
      }
      // Legacy format handling removed - only use modern case: format
      // Legacy format (chiffre:DIGIT,VALUE) is deprecated and should not be used
      // when case:student format is available
    }
  }

  return {
    bubbles,
    questions,
    studentId: Object.keys(studentIdBubbles).length > 0 ? studentIdBubbles : null,
    versionCode: Object.keys(versionCodeBubbles).length > 0 ? versionCodeBubbles : null,
    meta: {
      header,
      totalBubbles: bubbles.length,
      totalQuestions: Object.keys(questions).length,
      unit: 'pdf_points',
      pageHeightPt,
    },
  };
}

/**
 * Read .calage.xy from file path and parse
 * @param {string} filePath - absolute Windows path
 * @param {fs} fsModule - fs module (for testability)
 * @returns {Promise<Object>} parsed data
 */
async function readAndParseCalage(filePath, fsModule = require('fs')) {
  const fs = fsModule;
  if (!fs.existsSync(filePath)) {
    throw new Error(`Calage file not found: ${filePath}`);
  }
  const content = fs.readFileSync(filePath, 'utf8');
  return parseCalage(content);
}

/**
 * Scale calage coordinates from PDF points to target DPI
 * @param {Object} calageData - result of parseCalage()
 * @param {number} targetDpi - target DPI (default 300 for mobile scans)
 * @returns {Object} scaled data
 */
function scaleCalage(calageData, targetDpi = 300) {
  if (!calageData) {
    return {
      bubbles: [],
      questions: {},
      meta: { scale: targetDpi / PDF_PT_PER_INCH, targetDpi, sourceDpi: PDF_PT_PER_INCH },
    };
  }

  const scale = targetDpi / PDF_PT_PER_INCH;
  const scaled = {
    bubbles: calageData.bubbles.map((b) => ({
      ...b,
      // Y is already flipped during parsing, now scale both axes
      x: Math.round(b.x * scale),
      y: Math.round(b.y * scale),
      w: Math.round(b.w * scale),
      h: Math.round(b.h * scale),
    })),
    questions: {},
    meta: {
      ...calageData.meta,
      scale,
      targetDpi,
      sourceDpi: PDF_PT_PER_INCH,
    },
  };

  for (const [qNum, qData] of Object.entries(calageData.questions)) {
    scaled.questions[qNum] = {
      questionNum: qData.questionNum,
      slots: {},
    };
    for (const [letter, bubble] of Object.entries(qData.slots)) {
      scaled.questions[qNum].slots[letter] = {
        ...bubble,
        x: Math.round(bubble.x * scale),
        y: Math.round(bubble.y * scale),
        w: Math.round(bubble.w * scale),
        h: Math.round(bubble.h * scale),
      };
    }
  }

  // Scale student ID and version code coordinates
  if (calageData.studentId) {
    scaled.studentId = {};
    for (const [digitStr, values] of Object.entries(calageData.studentId)) {
      scaled.studentId[digitStr] = {};
      for (const [valStr, coords] of Object.entries(values)) {
        scaled.studentId[digitStr][valStr] = {
          x: Math.round(coords.x * scale),
          y: Math.round(coords.y * scale),
          w: Math.round(coords.w * scale),
          h: Math.round(coords.h * scale),
        };
      }
    }
  }

  if (calageData.versionCode) {
    scaled.versionCode = {};
    for (const [digitStr, values] of Object.entries(calageData.versionCode)) {
      scaled.versionCode[digitStr] = {};
      for (const [valStr, coords] of Object.entries(values)) {
        scaled.versionCode[digitStr][valStr] = {
          x: Math.round(coords.x * scale),
          y: Math.round(coords.y * scale),
          w: Math.round(coords.w * scale),
          h: Math.round(coords.h * scale),
        };
      }
    }
  }

  return scaled;
}

module.exports = {
  parseCalage,
  readAndParseCalage,
  scaleCalage,
  PDF_DPI: PDF_PT_PER_INCH,
  A4_HEIGHT_PT,
  spToPt,
};
