/**
 * AMC Calage Parser v2
 * Parse .calage.xy file generated by AMC to extract bubble coordinates
 * and convert to templateJson for mobile OMR scanning
 *
 * Format .calage.xy (AMC 1.x, v2023+):
 *   \tracepos{page:label}{x}{y}{shape}
 *   \boxchar{page:label}{char}
 *
 * Label formats:
 *   - Student ID: case:student[7]:1,1 = digit 7, value 1
 *   - Version: case:ver[1]:8,1 = version digit 1, position 8, value 1
 *              case:ver2[1]:9,1 = version digit 2, position 9, value 1
 *   - Questions: case:q1[1]:10,1 = question q1, position 10, value 1 (A)
 */

const SCALED_POINTS_PER_PT = 65536;
const PDF_PT_PER_INCH = 72;
const A4_HEIGHT_PT = 842;
const DEFAULT_SCAN_DPI = 300;

// ============================================================
// STEP 1: Parse raw .calage.xy content
// ============================================================

/**
 * Convert sp (scaled points) to PDF points
 */
function spToPt(sp) {
  return parseFloat(sp) / SCALED_POINTS_PER_PT;
}

/**
 * Parse raw .calage.xy text content
 * @param {string} content - raw file content
 * @returns {Object} parsed bubble data
 */
function parseCalage(content) {
  if (!content || typeof content !== 'string') {
    console.log('[calageToTemplate] WARNING: Empty or invalid calage content');
    return { bubbles: [], questions: {}, studentId: null, versionCode: null, meta: {} };
  }

  console.log('[calageToTemplate] Parsing calage.xy content...');
  console.log(`[calageToTemplate] Content length: ${content.length} chars`);

  // Group all tracepos entries by label
  // Each bubble has 2 entries: top-left and bottom-right corners
  const traceposByLabel = {};
  let pageHeightPt = A4_HEIGHT_PT;
  let header = null;

  const lines = content.split(/\r?\n/);
  let traceposCount = 0;
  
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) continue;

    // Capture header
    if (line.startsWith('\\version{')) {
      header = line;
      continue;
    }

    // Parse page dimensions: \page{...}{heightpt}
    const pageMatch = line.match(/^\\page\{[^}]+\}\{[^}]+\}\{([^}]+)pt\}/);
    if (pageMatch) {
      pageHeightPt = parseFloat(pageMatch[1]) || A4_HEIGHT_PT;
      continue;
    }

    // Parse \tracepos{page:label}{x}{y}{shape}
    const traceMatch = line.match(/^\\tracepos\{([^}]+)\}\{([^}]+)\}\{([^}]+)\}\{([^}]+)\}/);
    if (!traceMatch) continue;

    const [, label, xSp, ySp, shape] = traceMatch;

    // Skip position markers
    if (label.includes('position')) continue;

    // Convert sp to PDF points
    const xPt = spToPt(xSp);
    const yPt = spToPt(ySp);

    // Store by label for pairing
    if (!traceposByLabel[label]) {
      traceposByLabel[label] = [];
    }
    traceposByLabel[label].push({ x: xPt, y: yPt, shape });
    traceposCount++;
  }

  console.log(`[calageToTemplate] Found ${traceposCount} tracepos entries, ${Object.keys(traceposByLabel).length} unique labels`);

  // Parse boxchar entries to build label → option letter mapping
  // Format: \boxchar{0/1:case:q1[4]:10,1}{A}
  const labelToOption = {};
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line.startsWith('\\boxchar{')) continue;
    
    const boxMatch = line.match(/^\\boxchar\{([^}]+)\}\{([^}]+)\}/);
    if (!boxMatch) continue;
    
    const [, label, optionChar] = boxMatch;
    const actualLabel = label.replace(/^\d+\/\d+:/, '');
    labelToOption[actualLabel] = optionChar;
  }
  console.log(`[calageToTemplate] Boxchar entries: ${Object.keys(labelToOption).length}, sample:`, 
    Object.entries(labelToOption).slice(0, 3).map(([k,v]) => `${k}=${v}`).join(', '));

  // Process paired tracepos entries
  const studentIdBubbles = {};
  const versionCodeBubbles = {};
  const questionBubbles = [];
  const questions = {};

  for (const [label, points] of Object.entries(traceposByLabel)) {
    if (points.length < 2) continue;

    // Remove page prefix: "0/1:" or "0/2:"
    const actualLabel = label.replace(/^\d+\/\d+:/, '');
    
    // Sort points to identify corners (top-left vs bottom-right)
    const sorted = [...points].sort((a, b) => (a.x + a.y) - (b.x + b.y));
    const topLeft = sorted[0];
    const bottomRight = sorted[sorted.length - 1];
    
    const w = Math.abs(bottomRight.x - topLeft.x);
    const h = Math.abs(bottomRight.y - topLeft.y);

    // Parse label format: type:name[index]:position,value
    // Examples:
    //   case:student[7]:1,1
    //   case:ver[1]:8,1
    //   case:ver2[1]:9,1
    //   case:q1[1]:10,1
    //   chiffre:1,5 (legacy)
    const caseMatch = actualLabel.match(/^case:([^:[]+)(?:\[(\d+)\])?:(\d+),(\d+)$/);
    
    if (caseMatch) {
      const [, name, indexStr, posStr, valueStr] = caseMatch;
      const position = parseInt(posStr, 10);
      const value = parseInt(valueStr, 10);

      // Student ID field
      if (name === 'student' || name.match(/^chiffre\d*$/)) {
        const digit = parseInt(indexStr || '1', 10);
        if (!studentIdBubbles[digit]) studentIdBubbles[digit] = {};
        studentIdBubbles[digit][value] = {
          x: topLeft.x,
          y: topLeft.y,
          w: Math.round(w),
          h: Math.round(h),
          digit,
          value,
        };
        continue;
      }

      // Version code field
      // ver[1] → digit 1, ver2[1] → digit 2
      const verMatch = name.match(/^ver(\d*)$/);
      if (verMatch) {
        // If name is "ver" (no number), use bracket index as digit
        // If name is "ver2", digit is 2
        let verDigit;
        if (verMatch[1]) {
          verDigit = parseInt(verMatch[1], 10);
        } else if (indexStr) {
          verDigit = parseInt(indexStr, 10);
        } else {
          verDigit = position;
        }
        
        if (!versionCodeBubbles[verDigit]) versionCodeBubbles[verDigit] = {};
        versionCodeBubbles[verDigit][value] = {
          x: topLeft.x,
          y: topLeft.y,
          w: Math.round(w),
          h: Math.round(h),
          digit: verDigit,
          value,
        };
        continue;
      }

      // Question bubble: q1, q2, etc.
      // Get option letter from boxchar mapping
      const qMatch = name.match(/^q(\d+)$/);
      if (qMatch) {
        const qNum = parseInt(qMatch[1], 10);
        // Use boxchar mapping for accurate option letter
        const optionLetter = labelToOption[actualLabel] || 'A';

        const bubble = {
          id: `${qNum}:${optionLetter}`,
          questionNum: qNum,
          position,
          value,
          optionLetter,
          x: topLeft.x,
          y: topLeft.y,
          w: Math.round(w),
          h: Math.round(h),
          type: 'box',
        };

        questionBubbles.push(bubble);

        if (!questions[qNum]) {
          questions[qNum] = { questionNum: qNum, slots: {} };
        }
        questions[qNum].slots[optionLetter] = bubble;
      }
    }
    
  // Legacy format: chiffre:DIGIT,VALUE
  // NOTE: Skip legacy format if we already have case:student entries for this digit
  // This prevents duplicate bubbles (both formats exist in some AMC files)
  else if (actualLabel.startsWith('chiffre:')) {
    // Check if this digit already has case:student entries
    const chiffreMatch = actualLabel.match(/^chiffre:(\d+),(\d+)$/);
    if (chiffreMatch) {
      const legacyDigit = parseInt(chiffreMatch[1], 10);
      
      // If we already have case:student bubbles for this digit, skip legacy
      if (studentIdBubbles[legacyDigit] && Object.keys(studentIdBubbles[legacyDigit]).length > 0) {
        continue;
      }
      
      const digit = legacyDigit;
      const value = parseInt(chiffreMatch[2], 10);
      
      if (!studentIdBubbles[digit]) studentIdBubbles[digit] = {};
      studentIdBubbles[digit][value] = {
        x: topLeft.x,
        y: topLeft.y,
        w: Math.round(w),
        h: Math.round(h),
        digit,
        value,
      };
    }
  }
}

  return {
    bubbles: questionBubbles,
    questions,
    studentId: Object.keys(studentIdBubbles).length > 0 ? studentIdBubbles : null,
    versionCode: Object.keys(versionCodeBubbles).length > 0 ? versionCodeBubbles : null,
    meta: {
      header,
      totalBubbles: questionBubbles.length,
      totalQuestions: Object.keys(questions).length,
      unit: 'pdf_points',
      pageHeightPt,
    },
  };
}

// ============================================================
// STEP 2: Scale coordinates to target DPI
// ============================================================

/**
 * Scale calage coordinates from PDF points to target DPI
 * @param {Object} calageData - result of parseCalage()
 * @param {number} targetDpi - target DPI (default 300)
 * @returns {Object} scaled data
 */
function scaleCalage(calageData, targetDpi = 300) {
  if (!calageData) {
    return { bubbles: [], questions: {}, meta: {} };
  }
  
  const scale = targetDpi / PDF_PT_PER_INCH;

  const scaleCoords = (c) => ({
    x: Math.round(c.x * scale),
    y: Math.round(c.y * scale),
    w: Math.round(c.w * scale),
    h: Math.round(c.h * scale),
  });

  const scaled = {
    bubbles: calageData.bubbles.map(b => ({
      ...b,
      ...scaleCoords(b),
    })),
    questions: {},
    meta: {
      ...calageData.meta,
      scale,
      targetDpi,
      sourceDpi: PDF_PT_PER_INCH,
    },
  };

  for (const [qNum, qData] of Object.entries(calageData.questions)) {
    scaled.questions[qNum] = {
      questionNum: qData.questionNum,
      slots: {},
    };
    for (const [letter, bubble] of Object.entries(qData.slots)) {
      scaled.questions[qNum].slots[letter] = {
        ...bubble,
        ...scaleCoords(bubble),
      };
    }
  }

  if (calageData.studentId) {
    scaled.studentId = {};
    for (const [digitStr, values] of Object.entries(calageData.studentId)) {
      scaled.studentId[digitStr] = {};
      for (const [valStr, coords] of Object.entries(values)) {
        scaled.studentId[digitStr][valStr] = scaleCoords(coords);
      }
    }
  }

  if (calageData.versionCode) {
    scaled.versionCode = {};
    for (const [digitStr, values] of Object.entries(calageData.versionCode)) {
      scaled.versionCode[digitStr] = {};
      for (const [valStr, coords] of Object.entries(values)) {
        scaled.versionCode[digitStr][valStr] = scaleCoords(coords);
      }
    }
  }

  return scaled;
}

// ============================================================
// STEP 3: Build templateJson structure
// ============================================================

const PAPER_SIZES = {
  A4: { width: 595, height: 842 },
  A5: { width: 420, height: 595 },
};

/**
 * Build the answers section: coordinates of all bubbles per question
 * Format: { 'q1': { A: {x,y,w,h}, B: {...}, ... }, 'q2': {...}, ... }
 * 
 * AMC exports only correct answer bubble (A) in calage.xy.
 * This function generates positions for B, C, D based on existing bubble + spacing.
 */
function buildAnswersSection(scaledCalage, scale, csvData) {
  const answers = {};
  if (!scaledCalage || !scaledCalage.questions) return answers;

  // Get options per question from CSV metadata (default 4: A,B,C,D)
  const optionsPerQuestion = csvData?.meta?.optionsPerQuestion || 4;
  const optionLetters = ['A', 'B', 'C', 'D'].slice(0, optionsPerQuestion);

  // IMPORTANT: Calculate ACTUAL spacing from all bubbles in calage
  let actualSpacing = Math.round(25 * scale); // ~104px at 300 DPI (default)
  
  if (scaledCalage.bubbles && scaledCalage.bubbles.length >= 8) {
    const bubblesByQ = {};
    for (const bubble of scaledCalage.bubbles) {
      const qNum = bubble.questionNum;
      if (!bubblesByQ[qNum]) bubblesByQ[qNum] = [];
      bubblesByQ[qNum].push(bubble);
    }
    
    const spacings = [];
    for (const bubbles of Object.values(bubblesByQ)) {
      if (bubbles.length >= 2) {
        bubbles.sort((a, b) => a.x - b.x);
        for (let i = 1; i < bubbles.length; i++) {
          const spacing = bubbles[i].x - bubbles[i-1].x;
          if (spacing > 50 && spacing < 200) {
            spacings.push(spacing);
          }
        }
      }
    }
    
    if (spacings.length > 0) {
      spacings.sort((a, b) => a - b);
      actualSpacing = spacings[Math.floor(spacings.length / 2)];
    }
  }

  for (const [qNumStr, qData] of Object.entries(scaledCalage.questions)) {
    const qNum = parseInt(qNumStr, 10);
    if (isNaN(qNum) || qNum <= 0) continue;
    answers[`q${qNum}`] = {};

    // Collect existing bubbles (usually just the correct answer = A)
    const existingSlots = qData.slots || {};
    
    // Add existing bubbles (from AMC calage - typically only correct answer)
    for (const [letter, bubble] of Object.entries(existingSlots)) {
      answers[`q${qNum}`][letter] = {
        x: bubble.x,
        y: bubble.y,
        w: bubble.w,
        h: bubble.h,
      };
    }

    // Generate missing option bubbles (B, C, D)
    // Find reference bubble (prefer A if exists, otherwise first available)
    const referenceLetter = optionLetters.find(l => existingSlots[l]) || Object.keys(existingSlots)[0];
    const referenceBubble = existingSlots[referenceLetter];
    
    if (referenceBubble && optionsPerQuestion > 1) {
      const refIndex = optionLetters.indexOf(referenceLetter);
      const refX = referenceBubble.x;
      const refY = referenceBubble.y;
      const refW = referenceBubble.w || Math.round(15 * scale);
      const refH = referenceBubble.h || Math.round(15 * scale);

      for (let i = 0; i < optionLetters.length; i++) {
        const letter = optionLetters[i];
        if (!answers[`q${qNum}`][letter]) {
          // Generate position for this option based on reference
          const offsetFromRef = i - refIndex;
          const newX = refX + (offsetFromRef * actualSpacing);
          
          answers[`q${qNum}`][letter] = {
            x: newX,
            y: refY,
            w: refW,
            h: refH,
          };
        }
      }
    }
  }

  return answers;
}

/**
 * Build student ID field section
 * Format: { digits: n, coords: [{x, y, w, h, digit, value}, ...] }
 */
function buildStudentIdSection(existingCoords, options = {}) {
  const { digits = 7 } = options;

  if (!existingCoords) {
    return { digits, coords: null };
  }

  const coords = [];
  const studentIdData = existingCoords;
  
  // Sort digits numerically
  const sortedDigits = Object.keys(studentIdData)
    .map(Number)
    .sort((a, b) => a - b);
  
  for (const digit of sortedDigits) {
    const values = studentIdData[digit];
    if (!values) continue;
    
    // Sort values numerically
    const sortedValues = Object.keys(values)
      .map(Number)
      .sort((a, b) => a - b);
    
    for (const value of sortedValues) {
      const c = values[value];
      if (!c) continue;
      coords.push({
        x: Math.round(c.x * 100) / 100,
        y: Math.round(c.y * 100) / 100,
        w: Math.round(c.w * 100) / 100,
        h: Math.round(c.h * 100) / 100,
        digit,
        value,
      });
    }
  }
  
  return { digits, coords };
}

/**
 * Generate version code coordinates based on student ID position.
 * AMC places version code with VERTICAL layout (like student ID):
 * - Each digit has 10 values stacked vertically
 * - Digits are placed side by side horizontally
 */
function generateVersionCodeFromStudentId(studentIdCoords, digits = 2, scale = 1) {
  if (!studentIdCoords || studentIdCoords.length === 0) {
    return [];
  }

  // Find the first digit's first value position as reference
  let firstValue = null;
  for (const coord of studentIdCoords) {
    if (coord.digit === 1 && coord.value === 1) {
      firstValue = coord;
      break;
    }
  }

  if (!firstValue) {
    return [];
  }

  // Calculate vertical spacing from student ID bubbles
  // In PDF coordinates (top-left origin): larger y = higher on page (top)
  // Value 1 is at TOP (larger y), value 10 is at BOTTOM (smaller y)
  let verticalSpacing = 71; // default (bubble height + gap)
  for (const coord of studentIdCoords) {
    if (coord.digit === 1 && coord.value === 2) {
      verticalSpacing = Math.abs(Math.round(coord.y - firstValue.y));
      break;
    }
  }

  const refX = firstValue.x;
  const refY = firstValue.y;
  const refW = firstValue.w || 46;
  const refH = firstValue.h || 46;

  // Standard AMC spacing between version digits (horizontal)
  const DIGIT_SPACING_PT = 95; // in PDF points (~95 * 4.167 ≈ 396 pixels)

  const startX = refX + (DIGIT_SPACING_PT * scale);
  const coords = [];

  // Generate version code bubbles with VERTICAL stacking per digit
  // In PDF: larger y = top, smaller y = bottom
  // Value 1 at top (larger y), value 10 at bottom (smaller y)
  for (let digit = 1; digit <= digits; digit++) {
    const digitStartX = startX + ((digit - 1) * DIGIT_SPACING_PT * scale);
    for (let value = 1; value <= 10; value++) {
      // Stack vertically: y decreases as value increases (moving down the page)
      coords.push({
        x: Math.round(digitStartX * 100) / 100,
        y: Math.round((refY - (value - 1) * verticalSpacing) * 100) / 100,
        w: Math.round(refW * 100) / 100,
        h: Math.round(refH * 100) / 100,
        digit,
        value,
      });
    }
  }

  console.log(`[generateVersionCodeFromStudentId] Generated ${coords.length} version code bubbles (vertical stack, spacing=${verticalSpacing})`);
  return coords;
}

/**
 * Build version code field section
 * Format: { digits: n, coords: [{x, y, w, h, digit, value}, ...] }
 */
function buildVersionCodeSection(existingCoords, options = {}) {
  const { digits = 2 } = options;

  if (!existingCoords) {
    return { digits, coords: null };
  }

  const coords = [];
  const versionData = existingCoords;
  
  // Sort digits numerically
  const sortedDigits = Object.keys(versionData)
    .map(Number)
    .sort((a, b) => a - b);
  
  for (const digit of sortedDigits) {
    const values = versionData[digit];
    if (!values) continue;
    
    // Sort values numerically
    const sortedValues = Object.keys(values)
      .map(Number)
      .sort((a, b) => a - b);
    
    for (const value of sortedValues) {
      const c = values[value];
      if (!c) continue;
      coords.push({
        x: Math.round(c.x * 100) / 100,
        y: Math.round(c.y * 100) / 100,
        w: Math.round(c.w * 100) / 100,
        h: Math.round(c.h * 100) / 100,
        digit,
        value,
      });
    }
  }
  
  return { digits: sortedDigits.length || digits, coords };
}

/**
 * Build question scores section (equal scoring by default)
 * Format: { 'q1': score, 'q2': score, ... }
 */
function buildQuestionScores(numQuestions, totalScore = 10) {
  const scores = {};
  if (numQuestions <= 0) return scores;

  const scorePerQuestion = totalScore / numQuestions;

  for (let i = 1; i <= numQuestions; i++) {
    scores[`q${i}`] = Math.round(scorePerQuestion * 100) / 100;
  }

  return scores;
}

/**
 * Build answer key section from CSV data
 * Format: { 'q1': 'A', 'q2': 'B', ... }
 */
function buildAnswerKeySection(csvData) {
  const key = {};
  if (!csvData || !csvData.answers) return key;
  
  for (const [qNumStr, data] of Object.entries(csvData.answers)) {
    const qNum = parseInt(qNumStr, 10);
    if (isNaN(qNum) || qNum <= 0) continue;
    key[`q${qNum}`] = (data.correctOptions[0] || '').toUpperCase();
  }
  return key;
}

/**
 * Main builder: construct templateJson from calage + CSV data
 */
function buildTemplate(input) {
  const {
    calageData,
    csvData,
    exam,
    options = {},
  } = input;

  const {
    scanDpi = DEFAULT_SCAN_DPI,
    paperSize = 'A4',
    studentIdDigits = 7,
    versionDigits = 2,
  } = options;

  // Parse calage if raw content provided
  let parsedCalage = calageData;
  if (typeof calageData === 'string') {
    parsedCalage = parseCalage(calageData);
  }

  const totalScore = exam?.totalScore || 10;
  const numQuestions = parsedCalage?.meta?.totalQuestions || csvData?.meta?.totalQuestions || 0;
  
  // Scale calage from PDF points to target scan DPI
  const scaledCalage = scaleCalage(parsedCalage, scanDpi);
  const scale = scanDpi / PDF_PT_PER_INCH;

  const paperDims = PAPER_SIZES[paperSize] || PAPER_SIZES.A4;
  const pageWidth = Math.round(paperDims.width * scale);
  const pageHeight = Math.round(paperDims.height * scale);

  // Reference bubble size (from first question, first option)
  const firstBubble = scaledCalage.bubbles[0] || { w: 15, h: 15 };
  const bubbleWidth = Math.round(firstBubble.w * 100) / 100;
  const bubbleHeight = Math.round(firstBubble.h * 100) / 100;

  // Build sections
  const answers = buildAnswersSection(scaledCalage, scale, csvData);
  const answerKey = buildAnswerKeySection(csvData);
  const questionScores = buildQuestionScores(numQuestions, totalScore);

  // Build student ID and version code sections
  const studentIdSection = buildStudentIdSection(scaledCalage.studentId, {
    digits: studentIdDigits,
  });
  
  // Build version code section
  let versionCodeSection = buildVersionCodeSection(scaledCalage.versionCode, {
    digits: versionDigits,
  });
  
  // Fallback: generate version code bubbles based on student ID position
  if (!versionCodeSection.coords || versionCodeSection.coords.length === 0) {
    console.log('[calageToTemplate] No versionCode in calage, generating from student ID position...');
    const generatedCoords = generateVersionCodeFromStudentId(
      studentIdSection.coords,
      versionDigits,
      scale
    );
    if (generatedCoords.length > 0) {
      versionCodeSection = {
        digits: versionDigits,
        coords: generatedCoords,
      };
    }
  }

  // Validate coordinates don't overflow page
  const validateCoords = (coords, fieldName) => {
    if (!coords || !Array.isArray(coords)) return;
    for (const c of coords) {
      if (c.x + c.w > pageWidth) {
        console.warn(`[buildTemplate] WARNING: ${fieldName} x(${c.x}) + w(${c.w}) = ${c.x + c.w} > pageWidth(${pageWidth})`);
      }
      if (c.y + c.h > pageHeight) {
        console.warn(`[buildTemplate] WARNING: ${fieldName} y(${c.y}) + h(${c.h}) = ${c.y + c.h} > pageHeight(${pageHeight})`);
      }
    }
  };
  validateCoords(studentIdSection.coords, 'studentId');
  validateCoords(versionCodeSection.coords, 'versionCodeZone');

  return {
    examId: exam?._id ? exam._id.toString() : '',
    title: exam?.title || '',
    paperSize,
    scanDpi,
    scale: Math.round(scale * 10000) / 10000,
    pageWidth,
    pageHeight,
    bubbleWidth,
    bubbleHeight,
    studentId: studentIdSection,
    versionCodeZone: versionCodeSection,
    answers,
    answerKey,
    questionScores,
    totalScore,
    numberOfQuestions: numQuestions,
    preProcessors: [
      { name: 'Levels', options: { inBlack: 15.0, inWhite: 200.0, outBlack: 0.0, outWhite: 255.0, gamma: 1.0 } },
      { name: 'GaussianBlur', options: { kSize: [3, 3], sigmaX: 0 } },
      { name: 'CropPage', options: {} },
    ],
    autoAlign: false,
    generatedAt: new Date().toISOString(),
    source: 'amc-calage',
  };
}

// ============================================================
// EXPORTS
// ============================================================

module.exports = {
  parseCalage,
  scaleCalage,
  buildTemplate,
  buildAnswersSection,
  buildQuestionScores,
  buildAnswerKeySection,
  buildStudentIdSection,
  buildVersionCodeSection,
  DEFAULT_SCAN_DPI,
  PAPER_SIZES,
  PDF_DPI: PDF_PT_PER_INCH,
  A4_HEIGHT_PT,
  spToPt,
};
