import { create } from 'zustand';
import { apiService } from '../../core/api';
import { useAuthStore } from './authStore';
import env from '../../config/env';

// ─── Backend Types ─────────────────────────────────────────────────────────────

export interface ExamVersionQuestion {
  position: number;
  questionId: string;
  originalPosition: number;
  shuffledOptions: Array<{ id: string; text: string; isCorrect?: boolean }>;
}

export interface ExamVersion {
  _id: string;
  examId: string;
  versionCode: string;
  numberOfQuestions: number;
  questionIds: string[];
  questions?: ExamVersionQuestion[];
  distribution: Record<string, number>;
  submissionCount: number;
  createdAt: string;
  // AMC fields
  paperEngine?: 'amc';
  pdfUrl?: string | null;
  answerSheetPdfUrl?: string | null;
  corrigePdfUrl?: string | null;
  generatedAt?: string | null;
  generationErrors?: string[];
  // Note: templateJson is NOT stored on ExamVersion anymore.
  // It lives on OMRTemplate.templateJson (returned via /exams/:id/template)
}

export interface ExamTemplateData {
  examId: string;
  versionCode: string;
  template: OMRTemplateJson | null;
  answerKey: Record<string, string>;
  totalScore: number;
  numberOfQuestions: number;
}

/**
 * OMRTemplate.templateJson — AMC-generated per-bubble coordinates
 * Used by mobile engine_v2 for OMR scanning.
 * Generated by: AMC → .calage.xy → buildTemplate() → OMRTemplate.templateJson
 */
export interface OMRTemplateJson {
  examId: string;
  title: string;
  paperSize: string;
  scanDpi: number;
  scale: number;
  pageWidth: number;
  pageHeight: number;
  bubbleWidth: number;
  bubbleHeight: number;
  /** Số báo danh bubble coords */
  studentId: { digits: number; coords: Array<{ x: number; y: number; w: number; h: number }> };
  /** Mã đề bubble coords */
  versionCodeZone: { digits: number; coords: Array<{ x: number; y: number; w: number; h: number }> };
  /** Bubble coords per question: answers["q1"] = { "A": {x,y,w,h}, "B": {...}, ... } */
  answers: Record<string, Record<string, { x: number; y: number; w: number; h: number }>>;
  /** Correct answers: answerKey["q1"] = "A" */
  answerKey: Record<string, string>;
  /** Scores per question: questionScores["q1"] = 0.5 */
  questionScores: Record<string, number>;
  totalScore: number;
  numberOfQuestions: number;
  autoAlign: boolean;
  generatedAt: string;
  source: string;
}

export interface ExamStatistics {
  totalExams: number;
  totalStudents: number;
  totalSubmissions: number;
  averageScore: number;
  submissionRate: number;
  statusBreakdown: {
    draft: number;
    published: number;
    in_progress: number;
    completed: number;
    archived: number;
  };
}

export interface ExamFilters {
  status?: string;
  classId?: string;
  subjectId?: string;
  search?: string;
  startDate?: string;
  endDate?: string;
  page?: number;
  limit?: number;
}

export interface CreateExamPayload {
  title: string;
  description?: string;
  classIds: string[];
  primaryClassId?: string;
  subjectId?: string;
  subjectName?: string;
  omrTemplateId?: string;
  examDate?: string;
  startTime?: string;
  duration?: number;
  totalScore?: number;
  passingScore?: number;
  numberOfQuestions?: number;
  numberOfVersions?: number;
  questionIds?: string[];
  status?: 'draft' | 'published' | 'in_progress' | 'completed';
  shuffleConfig?: { shuffleQuestions: boolean; shuffleOptions: boolean };
  printConfig?: { paperSize: string; questionsPerPage: number; includeAnswerSheet: boolean };
}

export interface ClassRef {
  _id: string;
  name: string;
  code?: string;
  studentCount?: number;
}

export interface Question {
  _id: string;
  id?: string;
  content?: string;
  options?: Array<{ id: string; text: string; isCorrect?: boolean }>;
  correctAnswer?: string;
  imageUrl?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
  score?: number;
  type?: string;
}

export interface Exam {
  _id: string;
  title: string;
  description?: string;
  status: 'draft' | 'published' | 'in_progress' | 'completed' | 'archived';
  classId?: string;
  classIds?: Array<ClassRef | string>;
  primaryClassId?: ClassRef | string;
  subjectId?: string | { _id: string; name: string; color?: string };
  subjectName?: string;
  subjectColor?: string;
  examDate?: string;
  date?: string;
  startTime?: string;
  duration?: number;
  totalScore?: number;
  passingScore?: number;
  numberOfQuestions?: number;
  questionIds?: (string | Question)[];
  numberOfVersions?: number;
  totalSubmissions?: number;
  totalStudents?: number;
  createdBy?: { _id: string; name: string; email?: string };
  createdAt?: string;
  updatedAt?: string;
  publishedAt?: string;
  completedAt?: string;
  omrTemplateId?: { _id: string; name: string; code?: string };
  printConfig?: {
    paperSize?: string;
    questionsPerPage?: number;
    includeAnswerSheet?: boolean;
    schoolHeader?: boolean;
  };
  shuffleConfig?: {
    shuffleQuestions?: boolean;
    shuffleOptions?: boolean;
  };
}

// ─── Store ─────────────────────────────────────────────────────────────────────

interface ExamState {
  // Legacy list state
  exams: Exam[];
  isLoading: boolean;
  error: string | null;

  // New: single exam detail
  currentExam: Exam | null;
  examVersions: ExamVersion[];
  examStatistics: ExamStatistics | null;
  examTemplate: ExamTemplateData | null;
  isLoadingDetail: boolean;
  isPublishing: boolean;
  isCompleting: boolean;
  isGeneratingVersions: boolean;
  isCompiling: boolean;
  isLoadingTemplate: boolean;

  // Legacy methods
  fetchExams: (params?: { status?: string; classId?: string }) => Promise<void>;
  createExam: (exam: CreateExamPayload) => Promise<Exam | null>;
  updateExam: (exam: Exam) => Promise<void>;
  deleteExam: (examId: string) => Promise<void>;

  // New methods
  fetchExamById: (id: string) => Promise<void>;
  publishExam: (id: string) => Promise<void>;
  completeExam: (id: string) => Promise<void>;
  generateExamVersions: (id: string, count?: number) => Promise<void>;
  addClassesToExam: (id: string, classIds: string[]) => Promise<void>;
  removeClassesFromExam: (id: string, classIds: string[]) => Promise<void>;
  fetchExamVersions: (id: string) => Promise<void>;
  fetchExamVersionsFull: (id: string) => Promise<void>;
  generatePapers: (id: string, options?: { forceRegenerate?: boolean }) => Promise<any>;
  exportExamPdf: (id: string) => Promise<any>;
  exportVersionPdf: (examId: string, versionCode: string) => Promise<any>;
  exportResults: (id: string, format?: string) => Promise<any>;
  fetchExamTemplate: (id: string) => Promise<ExamTemplateData | null>;
  downloadExamTemplateJson: (id: string) => Promise<void>;

  // Utility
  clearCurrentExam: () => void;
  clearError: () => void;
}

export const useExamStore = create<ExamState>((set) => ({
  // Legacy
  exams: [],
  isLoading: false,
  error: null,

  // New state
  currentExam: null,
  examVersions: [],
  examStatistics: null,
  examTemplate: null,
  isLoadingDetail: false,
  isPublishing: false,
  isCompleting: false,
  isGeneratingVersions: false,
  isCompiling: false,
  isLoadingTemplate: false,

  // ─── Legacy Methods ────────────────────────────────────────────────────────────

  fetchExams: async (params) => {
    set({ isLoading: true, error: null });
    try {
      const queryParams: Record<string, string | number> = { limit: 100 };
      if (params?.status) queryParams.status = params.status;
      if (params?.classId) queryParams.classId = params.classId;

      const response = await apiService.get<any>('/exams', { params: queryParams });
      const examList = response.results || response || [];

      const mappedExams = examList.map((e: any) => ({
        _id: e._id,
        title: e.title,
        description: e.description,
        status: e.status || 'draft',
        classId: e.primaryClassId?._id || e.classIds?.[0]?._id || e.classId || '',
        classIds: e.classIds || [],
        primaryClassId: e.primaryClassId,
        subjectId: e.subjectId,
        subjectName: e.subjectId?.name || '',
        subjectColor: e.subjectId?.color || '',
        examDate: e.examDate || '',
        date: e.examDate || '',
        duration: e.duration || 0,
        totalScore: e.totalScore || 10,
        numberOfQuestions: e.numberOfQuestions || e.questionIds?.length || 0,
        questionIds: e.questionIds || [],
        numberOfVersions: e.numberOfVersions || 0,
        totalSubmissions: e.totalSubmissions || 0,
        totalStudents: e.totalStudents || 0,
        createdBy: e.createdBy,
        createdAt: e.createdAt,
        updatedAt: e.updatedAt,
      }));

      set({ exams: mappedExams, isLoading: false });
    } catch (error) {
      set({ error: (error as Error).message, isLoading: false });
    }
  },

  createExam: async (exam) => {
    set({ isLoading: true, error: null });
    try {
      const response = await apiService.post<any>('/exams', exam);
      set({ isLoading: false });
      return response;
    } catch (error) {
      set({ error: (error as Error).message, isLoading: false });
      return null;
    }
  },

  updateExam: async (exam) => {
    set({ isLoading: true, error: null });
    try {
      await apiService.patch<any>(`/exams/${exam._id}`, exam);
      set({ isLoading: false });
    } catch (error) {
      set({ error: (error as Error).message, isLoading: false });
    }
  },

  deleteExam: async (examId) => {
    set({ isLoading: true, error: null });
    try {
      await apiService.delete(`/exams/${examId}`);
      set((state) => ({
        exams: state.exams.filter((e) => e._id !== examId),
        isLoading: false,
      }));
    } catch (error) {
      set({ error: (error as Error).message, isLoading: false });
    }
  },

  // ─── New Methods ───────────────────────────────────────────────────────────────

  fetchExamById: async (id) => {
    set({ isLoading: true, isLoadingDetail: true, error: null, currentExam: null });
    try {
      const response = await apiService.get<any>(`/exams/${id}`);
      set({
        currentExam: response,
        isLoading: false,
        isLoadingDetail: false,
      });
    } catch (error) {
      set({ error: (error as Error).message, isLoading: false, isLoadingDetail: false });
    }
  },

  publishExam: async (id) => {
    set({ isPublishing: true, error: null });
    try {
      const response = await apiService.post<any>(`/exams/${id}/publish`);
      set((state) => ({
        currentExam: state.currentExam
          ? { ...state.currentExam, status: 'published' }
          : null,
        exams: state.exams.map((e) =>
          e._id === id ? { ...e, status: 'published' } : e
        ),
        isPublishing: false,
      }));
      return response;
    } catch (error) {
      set({ error: (error as Error).message, isPublishing: false });
      throw error;
    }
  },

  completeExam: async (id) => {
    set({ isCompleting: true, error: null });
    try {
      const response = await apiService.post<any>(`/exams/${id}/complete`);
      set((state) => ({
        currentExam: state.currentExam
          ? { ...state.currentExam, status: 'completed' }
          : null,
        exams: state.exams.map((e) =>
          e._id === id ? { ...e, status: 'completed' } : e
        ),
        isCompleting: false,
      }));
      return response;
    } catch (error) {
      set({ error: (error as Error).message, isCompleting: false });
      throw error;
    }
  },

  generateExamVersions: async (id, count = 4) => {
    set({ isGeneratingVersions: true, error: null });
    try {
      await apiService.post<any>(`/exams/${id}/versions`, {
        count: count,
      });
      // Re-fetch versions so store has full ExamVersion objects (not just string codes)
      const versionsRes = await apiService.get<any>(`/exams/${id}/versions`);
      const versions: ExamVersion[] = Array.isArray(versionsRes) ? versionsRes : (versionsRes.results || []);
      set({
        examVersions: versions,
        isGeneratingVersions: false,
      });
    } catch (error) {
      set({ error: (error as Error).message, isGeneratingVersions: false });
      throw error;
    }
  },

  addClassesToExam: async (id, classIds) => {
    set({ isLoading: true, error: null });
    try {
      const response = await apiService.post<any>(`/exams/${id}/classes`, {
        classIds,
      });
      set((state) => ({
        currentExam: state.currentExam
          ? { ...state.currentExam, classIds: response.classIds || state.currentExam.classIds }
          : null,
        isLoading: false,
      }));
    } catch (error) {
      set({ error: (error as Error).message, isLoading: false });
      throw error;
    }
  },

  removeClassesFromExam: async (id, classIds) => {
    set({ isLoading: true, error: null });
    try {
      await apiService.delete(`/exams/${id}/classes`, { classIds });
      set((state) => ({
        currentExam: state.currentExam
          ? { ...state.currentExam, classIds: state.currentExam.classIds?.filter((cid) => {
              const currentId = typeof cid === 'string' ? cid : cid._id;
              return !classIds.includes(currentId);
            }) }
          : null,
        isLoading: false,
      }));
    } catch (error) {
      set({ error: (error as Error).message, isLoading: false });
      throw error;
    }
  },

  fetchExamVersions: async (id) => {
    set({ isLoadingDetail: true, error: null });
    try {
      const response = await apiService.get<any>(`/exams/${id}/versions`);
      const versions: ExamVersion[] = Array.isArray(response) ? response : (response.results || []);
      set({ examVersions: versions, isLoadingDetail: false });
    } catch (error) {
      set({ error: (error as Error).message, isLoadingDetail: false });
    }
  },

  fetchExamVersionsFull: async (id) => {
    set({ isLoadingDetail: true, error: null });
    try {
      const [examRes, versionsRes] = await Promise.all([
        apiService.get<Exam>(`/exams/${id}`),
        apiService.get<any>(`/exams/${id}/versions`),
      ]);
      const versions: ExamVersion[] = Array.isArray(versionsRes) ? versionsRes : (versionsRes.results || []);
      set({
        currentExam: examRes,
        examVersions: versions,
        isLoadingDetail: false,
      });
    } catch (error) {
      set({ error: (error as Error).message, isLoadingDetail: false });
    }
  },

  generatePapers: async (id, options = {}) => {
    set({ isCompiling: true, error: null });
    try {
      const response = await apiService.post<any>(`/exams/${id}/generate-papers`, {
        forceRegenerate: options.forceRegenerate || false,
      });
      // Re-fetch versions to get updated pdfUrl, paperEngine, generatedAt, etc.
      const versionsRes = await apiService.get<any>(`/exams/${id}/versions`);
      const versions: ExamVersion[] = Array.isArray(versionsRes) ? versionsRes : (versionsRes.results || []);
      set({ examVersions: versions, isCompiling: false });
      return response;
    } catch (error) {
      set({ error: (error as Error).message, isCompiling: false });
      throw error;
    }
  },

  exportExamPdf: async (id) => {
    const token = useAuthStore.getState().token || '';
    const response = await fetch(
      `${env.apiUrl}/exams/${id}/export?format=pdf`,
      { headers: { Authorization: `Bearer ${token}` } }
    );

    if (!response.ok) {
      const err = await response.json().catch(() => ({ message: 'Export failed' }));
      throw new Error(err.message || `Lỗi ${response.status}: Xuất đề thi thất bại`);
    }

    const contentType = response.headers.get('content-type') || '';
    if (!contentType.includes('application/pdf')) {
      const text = await response.text().catch(() => '');
      throw new Error(`Server trả về không phải PDF: ${contentType || 'unknown'} — ${text.slice(0, 100)}`);
    }

    const blob = await response.blob();
    if (blob.size === 0) throw new Error('File PDF rỗng (0 bytes)');
    const objectUrl = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = objectUrl;
    a.download = `exam.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(objectUrl);
  },

  exportVersionPdf: async (examId, versionCode) => {
    const token = useAuthStore.getState().token || '';
    const response = await fetch(
      `${env.apiUrl}/exams/${examId}/versions/${versionCode}/pdf`,
      { headers: { Authorization: `Bearer ${token}` } }
    );

    if (!response.ok) {
      const err = await response.json().catch(() => ({ message: 'Export failed' }));
      throw new Error(err.message || `Lỗi ${response.status}: Xuất phiên bản đề thi thất bại`);
    }

    const contentType = response.headers.get('content-type') || '';
    if (!contentType.includes('application/pdf')) {
      const text = await response.text().catch(() => '');
      throw new Error(`Server trả về không phải PDF: ${contentType || 'unknown'} — ${text.slice(0, 100)}`);
    }

    const blob = await response.blob();
    if (blob.size === 0) throw new Error('File PDF rỗng (0 bytes)');
    const objectUrl = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = objectUrl;
    a.download = `exam_version_${versionCode}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(objectUrl);
  },

  exportResults: async (id, format = 'pdf') => {
    const token = useAuthStore.getState().token || '';
    const endpoint = `${env.apiUrl}/exams/${id}/results/export?format=${format}`;
    const response = await fetch(endpoint, { headers: { Authorization: `Bearer ${token}` } });

    if (!response.ok) {
      const err = await response.json().catch(() => ({ message: 'Export failed' }));
      throw new Error(err.message || `Lỗi ${response.status}: Xuất kết quả thất bại`);
    }

    const contentType = response.headers.get('content-type') || '';

    if (contentType.includes('application/json')) {
      // Backend returns JSON with submissions array for non-PDF formats
      const data = await response.json();
      await import('../../features/reports/examReportExport').then(() => {
        const rows = [
          ['STT', 'Ho ten', 'Ma HS', 'Diem', 'Trang thai', 'Ngay nop'],
        ];
        (data.submissions || []).forEach((r: any, i: number) => {
          rows.push([
            i + 1,
            r.studentName || '—',
            r.studentCode || '—',
            r.percentage != null ? r.percentage.toFixed(1) + '%' : '—',
            r.status === 'completed' ? 'Hoan thanh' : r.status === 'scanned' ? 'Da quet' : 'Chua cham',
            r.submittedAt ? new Date(r.submittedAt).toLocaleDateString('vi-VN') : '—',
          ]);
        });
        // Use dynamic XLSX import if available
        import('xlsx').then(XLSXModule => {
          const XLSX = XLSXModule.utils;
          const ws = XLSX.aoa_to_sheet(rows);
          (ws as any)['!cols'] = [{ wch: 6 }, { wch: 30 }, { wch: 12 }, { wch: 10 }, { wch: 15 }, { wch: 15 }];
          const sheetName = 'Ket qua';
          const finalWb = { SheetNames: [sheetName], Sheets: { [sheetName]: ws } };
          XLSXModule.utils.book_append_sheet(finalWb as any, ws, sheetName);
          XLSXModule.writeFile(finalWb as any, `KetQua_${id}_${Date.now()}.xlsx`);
        });
      });
      return;
    }

    const blob = await response.blob();
    if (blob.size === 0) throw new Error('File rong (0 bytes)');

    let filename;
    if (contentType.includes('application/pdf')) {
      filename = `KetQua_${id}.pdf`;
    } else if (
      contentType.includes('spreadsheetml') ||
      contentType.includes('excel') ||
      contentType.includes('openxmlformats')
    ) {
      filename = `KetQua_${id}.xlsx`;
    } else {
      filename = `KetQua_${id}.bin`;
    }

    const objectUrl = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = objectUrl;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(objectUrl);
  },

  fetchExamTemplate: async (id) => {
    set({ isLoadingTemplate: true, error: null });
    try {
      const response = await apiService.get<ExamTemplateData>(`/exams/${id}/template`);
      const data: ExamTemplateData = {
        examId: response.examId || id,
        versionCode: response.versionCode || '',
        template: response.template || null,
        answerKey: response.answerKey || {},
        totalScore: response.totalScore || 0,
        numberOfQuestions: response.numberOfQuestions || 0,
      };
      set({ examTemplate: data, isLoadingTemplate: false });
      return data;
    } catch (error) {
      set({
        examTemplate: null,
        error: (error as Error).message,
        isLoadingTemplate: false,
      });
      return null;
    }
  },

  downloadExamTemplateJson: async (id) => {
    const token = useAuthStore.getState().token || '';
    const response = await fetch(
      `${env.apiUrl}/exams/${id}/template`,
      { headers: { Authorization: `Bearer ${token}` } }
    );

    if (!response.ok) {
      const err = await response.json().catch(() => ({ message: 'Download failed' }));
      throw new Error(err.message || `Lỗi ${response.status}: Tải template thất bại`);
    }

    const blob = await response.blob();
    if (blob.size === 0) throw new Error('File template rỗng (0 bytes)');
    const objectUrl = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = objectUrl;
    a.download = `omr_template_${id}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(objectUrl);
  },

  /**
   * Download the answer sheet PDF (generated by AMC)
   */
  downloadAnswerSheet: async (id: string) => {
    const token = useAuthStore.getState().token || '';
    
    // First, get the answer sheet URL
    const response = await fetch(
      `${env.apiUrl}/exams/${id}/answer-sheet`,
      { headers: { Authorization: `Bearer ${token}` } }
    );

    if (!response.ok) {
      const err = await response.json().catch(() => ({ message: 'Lỗi khi lấy thông tin phiếu trả lời' }));
      throw new Error(err.message || `Lỗi ${response.status}`);
    }

    const data = await response.json();
    const answerSheetUrl = data.answerSheetPdfUrl;

    if (!answerSheetUrl) {
      throw new Error('Chưa có phiếu trả lời. Vui lòng compile AMC trước.');
    }

    // If it's a Cloudinary URL, open in new tab
    if (/^https?:\/\//i.test(answerSheetUrl)) {
      window.open(answerSheetUrl, '_blank', 'noopener,noreferrer');
      return;
    }

    // Otherwise, download via API
    const fileResponse = await fetch(
      `${env.apiUrl}${answerSheetUrl}`,
      { headers: { Authorization: `Bearer ${token}` } }
    );

    if (!fileResponse.ok) {
      throw new Error('Lỗi khi tải phiếu trả lời');
    }

    const blob = await fileResponse.blob();
    if (blob.size === 0) throw new Error('File phiếu trả lời rỗng (0 bytes)');
    const objectUrl = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = objectUrl;
    a.download = `PhieuTraLoi_${id}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(objectUrl);
  },

  // ─── Utility ──────────────────────────────────────────────────────────────────

  clearCurrentExam: () => set({ currentExam: null, examVersions: [], examTemplate: null }),
  clearError: () => set({ error: null }),
}));
