const mongoose = require('mongoose');
const { Submission, Exam, ExamVersion, Question, User, StudentProgress } = require('../models');
const ApiError = require('../utils/ApiError');
const questionService = require('./question.service');
const notificationService = require('./notification.service');
const { parsePagination } = require('../utils/parsePagination');

/**
 * ============================================================
 * GRADING FLOW REDESIGN — Phase 1
 *
 * AMC exams: Mobile scans + grades locally, submits graded answers.
 *   → KHÔNG call pythonBridge. Store directly via createFromOMR().
 *
 * Legacy exams (paperEngine !== 'amc'):
 *   → Call pythonBridge for server-side OMR scan + grade.
 *   → Mobile submits originalUrl + image; python returns detected answers.
 *
 * Template source of truth: OMRTemplate.templateJson (for AMC)
 *   → generated by AMC via examPaperService → buildTemplate()
 *   → Contains per-bubble {x,y,w,h} + answerKey for mobile engine_v2
 *
 * answerKey source of truth: ExamVersion.answerKey (Map<position, option>)
 *   → generated during generateVersions()
 *   → Used by backend to grade or verify mobile-submitted answers
 * ============================================================
 */

class SubmissionService {
  /**
   * Check if an exam uses AMC paper generation.
   * AMC exams: mobile scans locally using engine_v2 + templateJson,
   *            then submits pre-graded answers to /submissions.
   */
  async _isAmcExam(examId) {
    try {
      const { Exam } = require('../models');
      const exam = await Exam.findById(examId).select('paperEngine').lean();
      return exam?.paperEngine === 'amc';
    } catch {
      return false;
    }
  }

  /**
   * Create submission from mobile scanner result.
   * This is a simplified wrapper for AMC exams where mobile has already graded.
   */
  async create(data, userId, auditContext = {}) {
    let { examId, classId, versionCode, studentCode, answers,
      totalScore, maxScore, originalUrl, originalPublicId,
      annotatedUrl, annotatedPublicId, deviceInfo } = data;

    // Normalize: answers might be a JSON-encoded string
    if (typeof answers === 'string') {
      try {
        answers = JSON.parse(answers);
      } catch {
        // Not JSON — leave as-is
      }
    }

    // Validate required fields
    if (!examId) {
      throw new ApiError(400, 'examId is required');
    }
    if (!answers || typeof answers !== 'object') {
      throw new ApiError(400, 'answers is required');
    }

    // Use scanOmrSheet which handles AMC path internally
    return this.scanOmrSheet({
      examId, classId,
      originalUrl, originalPublicId,
      annotatedUrl, annotatedPublicId,
      versionCode, studentCode,
      answers, totalScore, maxScore,
      deviceInfo
    });
  }

  /**
   * Scan an OMR sheet.
   *
   * AMC exam (paperEngine === 'amc'):
   *   Mobile has already scanned the image using engine_v2 with templateJson,
   *   graded the answers, and submits the result here.
   *   Expected payload: { examId, versionCode, studentCode, answers, totalScore }
   *
   * Legacy exam:
   *   Mobile captures the image, uploads it, and submits here.
   *   Backend uses pythonBridge to scan + grade server-side.
   */
  async scanOmrSheet(data) {
    const { examId, classId, originalUrl, originalPublicId,
      annotatedUrl, annotatedPublicId, imageMeta, image, deviceInfo,
      versionCode: clientVersionCode, studentCode: clientStudentCode,
      answers: clientAnswers, totalScore: clientTotalScore,
      maxScore: clientMaxScore
    } = data;

    const config = require('../config/config');
    const { assertIsCloudinaryUrl } = require('../utils/cloudinary.util');

    // ── 1. Validate exam ──────────────────────────────────────────────
    const exam = await Exam.findById(examId);
    if (!exam) {
      throw new ApiError(404, 'Exam not found');
    }

    const isAmc = await this._isAmcExam(examId);

    // ══════════════════════════════════════════════════════════════════
    // PATH A: AMC EXAM
    //   Mobile has scanned + graded using engine_v2 + templateJson.
    //   It submits pre-graded answers directly. No python needed.
    // ══════════════════════════════════════════════════════════════════
    if (isAmc) {
      return this._createFromMobileGraded(exam, data);
    }

    // ══════════════════════════════════════════════════════════════════
    // PATH B: LEGACY EXAM
    //   Mobile uploads image; backend runs pythonBridge OMR scan.
    //   This path supports old exams that predate AMC integration.
    // ══════════════════════════════════════════════════════════════════

    let pythonResult = null;

    // Cloudinary: download image → base64 → python
    if (config.upload.mode === 'cloudinary' && originalUrl) {
      assertIsCloudinaryUrl(originalUrl, config.cloudinary.cloud_name);
      let imageBase64;
      try {
        const axios = require('axios');
        const imageResponse = await axios.get(originalUrl, { responseType: 'arraybuffer' });
        imageBase64 = Buffer.from(imageResponse.data).toString('base64');
      } catch (downloadErr) {
        throw new ApiError(500, `Failed to download image from Cloudinary: ${downloadErr.message}`);
      }
      const pythonBridge = require('./pythonBridge.service');
      try {
        // Legacy flow: pass zones (mm config) for algorithmic bubble detection
        const omrTemplate = exam.omrTemplateId
          ? await (require('./omrTemplate.service')).getById(exam.omrTemplateId)
          : null;
        pythonResult = await pythonBridge.processImage({
          image: imageBase64,
          template: omrTemplate?.zones || {},
        });
      } catch (err) {
        throw new ApiError(500, `OMR processing failed: ${err.message}`);
      }
    } else if (image) {
      // base64 mode
      const pythonBridge = require('./pythonBridge.service');
      try {
        const omrTemplate = exam.omrTemplateId
          ? await (require('./omrTemplate.service')).getById(exam.omrTemplateId)
          : null;
        pythonResult = await pythonBridge.processImage({
          image,
          template: omrTemplate?.zones || {},
        });
      } catch (err) {
        throw new ApiError(500, `OMR processing failed: ${err.message}`);
      }
    } else {
      throw new ApiError(400, 'originalUrl or image is required');
    }

    if (!pythonResult || !pythonResult.success) {
      throw new ApiError(500, pythonResult?.error || 'OMR scanning returned no result');
    }

    // ── Parse python result ──────────────────────────────────────────
    const {
      answers: rawAnswers = [],
      versionCode,
      studentCode,
      metadata: scanMeta = {},
    } = pythonResult;

    // ── Build graded answers ──────────────────────────────────────────
    const { gradedAnswers, versionId } = await this._buildGradedAnswers(
      exam, examId, rawAnswers, versionCode
    );

    // ── Resolve student ────────────────────────────────────────────────
    const studentId = await this._resolveStudent(classId, studentCode);

    // ── Save submission ───────────────────────────────────────────────
    const submission = await this._upsertSubmission({
      exam, examId, versionId, studentId, studentCode, classId,
      gradedAnswers, originalUrl, originalPublicId, deviceInfo, scanMeta,
    });

    // ── Post-processing ──────────────────────────────────────────────
    await this._postScanProcessing(exam, gradedAnswers, submission);

    const totalScore = gradedAnswers.reduce((sum, a) => sum + a.score, 0);

    return {
      status: 'scanned',
      submissionId: submission._id,
      examId,
      totalScore: Math.round(totalScore * 10) / 10,
      maxScore: exam.totalScore,
      answerCount: gradedAnswers.length,
      detectedAnswers: gradedAnswers.reduce((acc, a) => {
        if (a.selectedAnswer) acc[a.position.toString()] = a.selectedAnswer;
        return acc;
      }, {}),
      pythonResult,
    };
  }

  /**
   * PATH A handler: AMC exam — mobile already graded.
   * Mobile submits: versionCode, studentCode, answers{}, totalScore.
   */
  async _createFromMobileGraded(exam, data) {
    const { examId, classId, versionCode: clientVersionCode,
      studentCode: clientStudentCode, answers: clientAnswers,
      totalScore: clientTotalScore, maxScore: clientMaxScore,
      originalUrl, originalPublicId, annotatedUrl, annotatedPublicId,
      deviceInfo } = data;

    if (!clientAnswers || typeof clientAnswers !== 'object') {
      throw new ApiError(400, 'AMC exam requires pre-graded answers from mobile scanner');
    }

    // ── Resolve version ───────────────────────────────────────────────
    let versionId = null;
    if (clientVersionCode) {
      const version = await ExamVersion.findOne({
        examId, versionCode: clientVersionCode.toString()
      });
      if (version) versionId = version._id;
    }
    if (!versionId) {
      const firstVersion = await ExamVersion.findOne({ examId }).sort({ versionCode: 1 });
      if (firstVersion) versionId = firstVersion._id;
    }

    // ── Resolve answer key ────────────────────────────────────────────
    const answerKey = versionId ? await this._getAnswerKey(versionId) : {};

    // ── Build graded answers from mobile payload ───────────────────────
    const gradedAnswers = Object.entries(clientAnswers).map(([key, selected]) => {
      // Key format: "q1", "q2", etc. Extract position number
      const posStr = key.replace(/^q/i, '');
      const pos = parseInt(posStr, 10);
      if (isNaN(pos)) return null;
      
      const selectedAnswer = selected || null;
      const correct = answerKey[pos] || null;
      // isCorrect can only be true if we have both selected and correct answer
      const isCorrect = selectedAnswer !== null && correct !== null && selectedAnswer === correct;
      const scorePerQuestion = exam.totalScore / exam.numberOfQuestions;
      return {
        position: pos,
        questionId: null,
        selectedAnswer,
        correctAnswer: correct,
        isCorrect,
        score: isCorrect ? scorePerQuestion : 0,
        maxScore: scorePerQuestion,
        omrData: null,
      };
    }).filter(Boolean);

    // Sort by position
    gradedAnswers.sort((a, b) => a.position - b.position);

    // ── Resolve student ───────────────────────────────────────────────
    const studentId = await this._resolveStudent(classId, clientStudentCode);

    // ── Save submission ───────────────────────────────────────────────
    const submission = await this._upsertSubmission({
      exam, examId, versionId, studentId, studentCode: clientStudentCode,
      classId, gradedAnswers, originalUrl, originalPublicId,
      annotatedUrl, annotatedPublicId,
      deviceInfo, scanMeta: {},
    });

    // ── Post-processing ───────────────────────────────────────────────
    await this._postScanProcessing(exam, gradedAnswers, submission);

    const totalScore = clientTotalScore
      ?? gradedAnswers.reduce((sum, a) => sum + a.score, 0);

    return {
      status: 'scanned',
      submissionId: submission._id,
      examId,
      totalScore: Math.round(totalScore * 10) / 10,
      maxScore: clientMaxScore ?? exam.totalScore,
      answerCount: gradedAnswers.length,
      detectedAnswers: gradedAnswers.reduce((acc, a) => {
        if (a.selectedAnswer) acc[a.position.toString()] = a.selectedAnswer;
        return acc;
      }, {}),
    };
  }

  /**
   * Build graded answers from python result for legacy exams.
   */
  async _buildGradedAnswers(exam, examId, rawAnswers, versionCode) {
    let versionId = null;
    if (versionCode) {
      const version = await ExamVersion.findOne({
        examId, versionCode: versionCode.toString()
      });
      if (version) versionId = version._id;
    }
    if (!versionId) {
      const firstVersion = await ExamVersion.findOne({ examId }).sort({ versionCode: 1 });
      if (firstVersion) versionId = firstVersion._id;
    }

    const [versionQuestions, answerKey] = await Promise.all([
      versionId ? this._getVersionQuestions(versionId) : [],
      versionId ? this._getAnswerKey(versionId) : {},
    ]);

    const gradedAnswers = rawAnswers.map((raw, idx) => {
      const pos = idx + 1;
      const selected = raw.optionId || null;
      const versionQ = versionQuestions.find(vq => vq.position === pos);
      const questionId = versionQ?.questionId || null;
      const correct = answerKey[pos] || null;
      const isCorrect = selected !== null && selected === correct;
      const scorePerQuestion = exam.totalScore / exam.numberOfQuestions;
      return {
        position: pos,
        questionId,
        selectedAnswer: selected,
        correctAnswer: correct,
        isCorrect,
        score: isCorrect ? scorePerQuestion : 0,
        omrData: raw.omrData || null,
      };
    });

    return { gradedAnswers, versionId };
  }

  /**
   * Resolve student by studentCode within class.
   */
  async _resolveStudent(classId, studentCode) {
    if (!studentCode || !classId) return null;
    const classDoc = await (require('../models')).Class
      .findById(classId).select('studentIds').lean();
    if (!classDoc?.studentIds) return null;
    const students = await User.find({
      _id: { $in: classDoc.studentIds },
      studentCode: studentCode.toString(),
    }).select('_id');
    return students.length > 0 ? students[0]._id : null;
  }

  /**
   * Upsert submission (update if exists, create if new).
   */
  async _upsertSubmission({ exam, examId, versionId, studentId, studentCode,
    classId, gradedAnswers, originalUrl, originalPublicId,
    annotatedUrl, annotatedPublicId,
    deviceInfo, scanMeta }) {
    const existingFilter = studentId
      ? { examId: new mongoose.Types.ObjectId(examId), studentId }
      : { examId: new mongoose.Types.ObjectId(examId), studentCode: studentCode?.toString() };

    const existing = await Submission.findOne(existingFilter);
    const totalScore = gradedAnswers.reduce((sum, a) => sum + a.score, 0);

    if (existing) {
      existing.answers = gradedAnswers;
      existing.totalScore = totalScore;
      existing.maxScore = exam.totalScore;
      existing.finalScore = totalScore;
      existing.status = 'scanned';
      existing.versionId = versionId || existing.versionId;
      if (originalUrl || annotatedUrl) {
        existing.images = {
          ...existing.images,
          ...(originalUrl ? { original: { publicId: originalPublicId, url: originalUrl } } : {}),
          ...(annotatedUrl ? { annotated: { publicId: annotatedPublicId, url: annotatedUrl } } : {}),
        };
      }
      existing.scanMetadata = {
        ...existing.scanMetadata,
        deviceInfo: deviceInfo || null,
        scannedAt: new Date(),
        processingTimeMs: scanMeta.processingTimeMs || 0,
        ocr: scanMeta.ocr || {},
      };
      await existing.save();
      return existing;
    }

    const imagesObj = {};
    if (originalUrl) imagesObj.original = { publicId: originalPublicId, url: originalUrl };
    if (annotatedUrl) imagesObj.annotated = { publicId: annotatedPublicId, url: annotatedUrl };

    const submission = new Submission({
      examId,
      versionId: versionId || undefined,
      omrTemplateId: exam.omrTemplateId,
      studentId: studentId || undefined,
      studentCode: studentCode?.toString() || `anon-${Date.now()}`,
      classId: classId || undefined,
      answers: gradedAnswers,
      totalScore,
      maxScore: exam.totalScore,
      finalScore: totalScore,
      status: 'scanned',
      images: Object.keys(imagesObj).length > 0 ? imagesObj : undefined,
      scanMetadata: {
        deviceInfo: deviceInfo || null,
        scannedAt: new Date(),
        processingTimeMs: scanMeta.processingTimeMs || 0,
        ocr: scanMeta.ocr || {},
      },
    });
    await submission.save();
    return submission;
  }

  /**
   * Post-scan processing: update exam status, question stats, notify student.
   */
  async _postScanProcessing(exam, gradedAnswers, submission) {
    // Auto-transition exam to in_progress after first scan
    if (exam.status === 'published') {
      exam.status = 'in_progress';
      await exam.save();
    }

    // Update question difficulty stats
    for (const answer of gradedAnswers) {
      if (answer.questionId) {
        await questionService.updateDifficultyStats(answer.questionId, answer.isCorrect);
      }
    }

    // Notify student of score
    if (submission.studentId) {
      const totalScore = gradedAnswers.reduce((sum, a) => sum + a.score, 0);
      await notificationService.notifyScoreAvailable(
        submission.studentId.toString(),
        submission._id.toString(),
        exam._id.toString(),
        exam.title,
        Math.round(totalScore * 10) / 10,
        exam.totalScore
      );
    }
  }

  async _getVersionQuestions(versionId) {
    const version = await ExamVersion.findById(versionId)
      .select('questions')
      .lean();
    if (!version || !version.questions) return [];
    return version.questions.map(vq => ({
      position: vq.position,
      questionId: vq.questionId,
    }));
  }

  async _getAnswerKey(versionId) {
    const version = await ExamVersion.findById(versionId).lean();
    if (!version || !version.answerKey) return {};
    const map = version.answerKey instanceof Map
      ? version.answerKey
      : new Map(Object.entries(version.answerKey || {}));
    const result = {};
    for (const [pos, optId] of map.entries()) {
      result[parseInt(pos, 10)] = optId;
    }
    return result;
  }

  async createFromOMR(scanResult, userId) {
    const { examId, versionId, studentCode, answers, totalScore } = scanResult;

    const exam = await Exam.findById(examId).select('totalScore numberOfQuestions').lean();
    const maxScore = exam?.totalScore || 10;
    const scorePerQuestion = maxScore / (exam?.numberOfQuestions || answers.length || 1);

    const submission = new Submission({
      examId,
      versionId,
      studentId: userId,
      studentCode,
      answers,
      totalScore,
      maxScore,
      finalScore: totalScore,
      status: 'scanned',
    });

    await submission.save();

    // Update student progress
    await this.updateStudentProgress(userId, scanResult);

    // Update question difficulty stats
    for (const answer of answers) {
      if (answer.questionId) {
        await questionService.updateDifficultyStats(answer.questionId, answer.isCorrect);
      }
    }

    return submission;
  }

  async getById(id) {
    return Submission.findById(id)
      .populate('examId', 'title examDate duration')
      .populate('versionId', 'versionCode')
      .populate('studentId', 'name email studentCode')
      .populate('answers.questionId', 'content type options');
  }

  async getByExam(examId, query = {}) {
    const [results, total] = await Promise.all([
      Submission.find({ examId: new mongoose.Types.ObjectId(examId), ...query })
        .populate('examId', 'title examDate duration')
        .populate('versionId', 'versionCode')
        .populate('studentId', 'name email studentCode classIds')
        .populate('classId', 'name')
        .sort({ createdAt: -1 }),
      Submission.countDocuments({ examId: new mongoose.Types.ObjectId(examId) }),
    ]);

    return { results, total };
  }

  /**
   * Return submissions for an exam grouped by class. Recovering missing
   * classId from the related student's classIds[0] when the stored value is
   * null (legacy scans from before the classId field was populated).
   */
  async getExamSubmissionsByClass(examId) {
    const submissions = await Submission.find({ examId: new mongoose.Types.ObjectId(examId) })
      .populate('examId', 'title examDate duration')
      .populate('studentId', 'name email studentCode classIds')
      .populate('classId', 'name')
      .sort({ createdAt: -1 });

    const groups = new Map();
    for (const sub of submissions) {
      let classId = sub.classId?._id?.toString() || sub.classId?.toString() || null;
      let className = sub.classId?.name || null;

      if (!classId && sub.studentId && Array.isArray(sub.studentId.classIds) && sub.studentId.classIds.length > 0) {
        classId = sub.studentId.classIds[0].toString();
        className = className || 'Chưa xác định';
      }

      const key = classId || 'unknown';
      if (!groups.has(key)) {
        groups.set(key, {
          classId,
          className: className || 'Chưa xác định',
          submissions: [],
        });
      }
      groups.get(key).submissions.push(sub);
    }

    return {
      total: submissions.length,
      classes: Array.from(groups.values()),
    };
  }

  async getAll(query = {}) {
    const {
      examId,
      studentId,
      versionId,
      status,
      fromDate,
      toDate,
      page: _page,
      limit: _limit,
      sortBy,
      populate,
      ...rest
    } = query;
    const { page, limit, skip } = parsePagination(query);

    const filter = {};
    if (examId) filter.examId = new mongoose.Types.ObjectId(examId);
    if (studentId) filter.studentId = new mongoose.Types.ObjectId(studentId);
    if (versionId) filter.versionId = new mongoose.Types.ObjectId(versionId);
    if (status) filter.status = status;
    if (fromDate || toDate) {
      filter.createdAt = {};
      if (fromDate) filter.createdAt.$gte = new Date(fromDate);
      if (toDate) filter.createdAt.$lte = new Date(toDate);
    }

    const [results, total] = await Promise.all([
      Submission.find(filter)
        .populate('examId', 'title examDate')
        .populate('versionId', 'versionCode')
        .populate('studentId', 'name email studentCode')
        .populate('classId', 'name')
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit),
      Submission.countDocuments(filter),
    ]);

    return {
      results,
      page,
      limit,
      total,
      pages: Math.ceil(total / limit),
    };
  }

  async updateAnswers(id, answers) {
    const submission = await Submission.findById(id);
    if (!submission) {
      throw new ApiError(404, 'Submission not found');
    }

    const { Exam, ExamVersion } = require('../models');
    const exam = await Exam.findById(submission.examId).select('totalScore numberOfQuestions').lean();

    for (const [posStr, selectedAnswer] of Object.entries(answers)) {
      const position = parseInt(posStr, 10);
      const answer = submission.answers.find(a => a.position === position);
      if (!answer) continue;

      answer.selectedAnswer = selectedAnswer;

      // Re-grade
      if (answer.correctAnswer) {
        answer.isCorrect = selectedAnswer === answer.correctAnswer;
        const scorePerQuestion = (exam?.totalScore || 10) / (exam?.numberOfQuestions || 1);
        answer.score = answer.isCorrect ? scorePerQuestion : 0;
      }
    }

    submission.totalScore = submission.answers.reduce((sum, a) => sum + a.score, 0);
    submission.finalScore = submission.totalScore;
    submission.status = 'scanned';
    await submission.save();

    return {
      success: true,
      totalScore: Math.round(submission.totalScore * 10) / 10,
      maxScore: submission.maxScore,
    };
  }

  async manualOverride(id, data, userId) {
    const { position, correctedAnswer, reason } = data;

    const submission = await Submission.findById(id);
    if (!submission) {
      throw new ApiError(404, 'Submission not found');
    }

    // Find and update the answer
    const answer = submission.answers.find(a => a.position === position);
    if (!answer) {
      throw new ApiError(404, 'Answer at this position not found');
    }

    // Record override
    submission.manualOverrides.push({
      position,
      originalAnswer: answer.selectedAnswer,
      correctedAnswer,
      reason,
      overriddenBy: userId,
      overriddenAt: new Date(),
    });

    // Update answer
    answer.selectedAnswer = correctedAnswer;
    answer.isCorrect = correctedAnswer === answer.correctAnswer;
    answer.score = answer.isCorrect ? answer.score : 0;

    // Recalculate total
    submission.totalScore = submission.answers.reduce((sum, a) => sum + a.score, 0);
    submission.finalScore = submission.totalScore;

    await submission.save();
    return submission;
  }

  async getByStudent(studentId, query = {}) {
    const { page, limit, skip } = parsePagination(query);
    const [results, total] = await Promise.all([
      Submission.find({ studentId: new mongoose.Types.ObjectId(studentId) })
        .populate('examId', 'title examDate duration')
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit),
      Submission.countDocuments({ studentId: new mongoose.Types.ObjectId(studentId) }),
    ]);
    return { results, page, limit, total, pages: Math.ceil(total / limit) };
  }

  async getMy(studentId, query = {}) {
    const { page, limit, skip } = parsePagination(query);
    const { startDate, endDate, status } = query;
    const filter = { studentId: new mongoose.Types.ObjectId(studentId) };
    if (status) filter.status = status;
    if (startDate || endDate) {
      filter.createdAt = {};
      if (startDate) filter.createdAt.$gte = new Date(startDate);
      if (endDate) filter.createdAt.$lte = new Date(endDate + 'T23:59:59.999Z');
    }
    const [results, total] = await Promise.all([
      Submission.find(filter)
        .populate('examId', 'title examDate duration subjectName subjectColor')
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit),
      Submission.countDocuments(filter),
    ]);
    return { results, page, limit, total, pages: Math.ceil(total / limit) };
  }

  async delete(id) {
    const cloudinaryService = require('./cloudinary.service');
    const submission = await Submission.findById(id);
    if (!submission) return null;

    for (const type of ['original', 'preprocessed', 'annotated']) {
      const img = submission.images?.[type];
      if (img?.publicId) {
        try {
          await cloudinaryService.destroy(img.publicId);
        } catch (err) {
          // best-effort; do not fail the deletion
        }
      }
    }
    await Submission.findByIdAndDelete(id);
    return submission;
  }

  async attachImage(submissionId, userId, payload, auditContext) {
    const { UploadAuditLog } = require('../models');
    const config = require('../config/config');
    const { assertIsCloudinaryUrl } = require('../utils/cloudinary.util');

    const submission = await Submission.findById(submissionId);
    if (!submission) {
      throw new ApiError(404, 'Submission not found');
    }

    const { type, url, publicId, width, height, bytes, format } = payload;

    if (!['original', 'preprocessed', 'annotated'].includes(type)) {
      throw new ApiError(400, 'Invalid image type');
    }
    if (bytes != null && bytes > config.upload.maxBytes) {
      throw new ApiError(400, `Image exceeds max size of ${config.upload.maxBytes} bytes`);
    }

    assertIsCloudinaryUrl(url, config.cloudinary.cloud_name);

    submission.images = submission.images || {};
    submission.images[type] = {
      publicId,
      url,
      width,
      height,
      bytes,
      format,
      uploadedAt: new Date(),
    };
    await submission.save();

    if (UploadAuditLog) {
      await UploadAuditLog.create({
        userId,
        action: 'attach_image',
        submissionId: submission._id,
        imageType: type,
        publicId,
        cloudinaryUrl: url,
        bytes,
        ipAddress: auditContext?.ip,
        userAgent: auditContext?.userAgent,
      });
    }

    return submission;
  }

  async deleteImage(submissionId, userId, type, auditContext) {
    const { UploadAuditLog } = require('../models');
    const cloudinaryService = require('./cloudinary.service');

    const submission = await Submission.findById(submissionId);
    if (!submission) {
      throw new ApiError(404, 'Submission not found');
    }
    if (!['original', 'preprocessed', 'annotated'].includes(type)) {
      throw new ApiError(400, 'Invalid image type');
    }

    const img = submission.images?.[type];
    if (!img || !img.publicId) {
      throw new ApiError(404, `No image of type "${type}" on this submission`);
    }

    let destroyResult;
    try {
      destroyResult = await cloudinaryService.destroy(img.publicId);
    } catch (err) {
      if (UploadAuditLog) {
        await UploadAuditLog.create({
          userId,
          action: 'delete_image',
          submissionId: submission._id,
          imageType: type,
          publicId: img.publicId,
          error: err.message,
          ipAddress: auditContext?.ip,
          userAgent: auditContext?.userAgent,
        });
      }
      // Continue to clear DB record even if Cloudinary fails
    }

    submission.images[type] = undefined;
    await submission.save();

    if (UploadAuditLog) {
      await UploadAuditLog.create({
        userId,
        action: 'delete_image',
        submissionId: submission._id,
        imageType: type,
        publicId: img.publicId,
        cloudinaryUrl: img.url,
        ipAddress: auditContext?.ip,
        userAgent: auditContext?.userAgent,
      });
    }

    return { submission, destroyResult };
  }

  async getStatistics(examId) {
    const matchStage = { $match: { examId: new mongoose.Types.ObjectId(examId) } };

    const [stats, gradedSubmissions, exam] = await Promise.all([
      Submission.aggregate([
        matchStage,
        {
          $group: {
            _id: null,
            totalSubmissions: { $sum: 1 },
            totalStudents: { $addToSet: '$studentId' },
            averageScore: { $avg: '$totalScore' },
            highestScore: { $max: '$totalScore' },
            lowestScore: { $min: '$totalScore' },
          },
        },
      ]),
      Submission.aggregate([
        matchStage,
        { $match: { status: { $in: ['scanned', 'completed', 'graded', 'manual_review'] } } },
        {
          $bucket: {
            groupBy: '$totalScore',
            boundaries: [0, 2, 4, 6, 8, 10.01],
            default: 'Other',
            output: {
              count: { $sum: 1 },
            },
          },
        },
      ]),
      Exam.findById(examId).select('totalStudents totalSubmissions').lean(),
    ]);

    const base = stats[0] || { totalSubmissions: 0, averageScore: 0, highestScore: 0, lowestScore: 0, totalStudents: [] };
    const examTotalStudents = exam?.totalStudents || 0;

    const gradeDistribution = [
      { grade: 'Kém (0-2)', count: 0, percentage: 0 },
      { grade: 'Yếu (2-4)', count: 0, percentage: 0 },
      { grade: 'Trung bình (4-6)', count: 0, percentage: 0 },
      { grade: 'Khá (6-8)', count: 0, percentage: 0 },
      { grade: 'Giỏi (8-10)', count: 0, percentage: 0 },
    ];

    const bucketMap = {};
    for (const b of gradedSubmissions) {
      if (b._id !== undefined) bucketMap[b._id] = b.count;
    }
    gradeDistribution[0].count = bucketMap[0] || 0;
    gradeDistribution[1].count = bucketMap[2] || 0;
    gradeDistribution[2].count = bucketMap[4] || 0;
    gradeDistribution[3].count = bucketMap[6] || 0;
    gradeDistribution[4].count = bucketMap[10] || 0;

    const totalGraded = gradeDistribution.reduce((s, d) => s + d.count, 0);
    for (const d of gradeDistribution) {
      d.percentage = totalGraded > 0 ? Math.round((d.count / totalGraded) * 100) : 0;
    }

    const passGrade = gradeDistribution.slice(2).reduce((s, d) => s + d.count, 0);
    const passRate = totalGraded > 0 ? Math.round((passGrade / totalGraded) * 100) : 0;

    const submissionRate = examTotalStudents > 0
      ? Math.round((base.totalSubmissions / examTotalStudents) * 100)
      : 0;

    const scoreHistogram = [
      { range: '0-2', count: gradeDistribution[0].count },
      { range: '2-4', count: gradeDistribution[1].count },
      { range: '4-6', count: gradeDistribution[2].count },
      { range: '6-8', count: gradeDistribution[3].count },
      { range: '8-10', count: gradeDistribution[4].count },
    ];

    return {
      totalSubmissions: base.totalSubmissions,
      totalStudents: examTotalStudents,
      submissionRate,
      averageScore: Math.round((base.averageScore || 0) * 10) / 10,
      highestScore: base.highestScore || 0,
      lowestScore: base.lowestScore || 0,
      gradeDistribution,
      scoreHistogram,
      passRate,
    };
  }

  async updateStudentProgress(studentId, scanResult) {
    const student = await User.findById(studentId);
    if (!student) return;

    let progress = await StudentProgress.findOne({ studentId });

    if (!progress) {
      progress = new StudentProgress({
        studentId,
        schoolId: student.schoolId,
      });
    }

    const exam = await Exam.findById(scanResult.examId);
    if (!exam) return;

    const scoreHistory = {
      examId: exam._id,
      submissionId: scanResult._id,
      score: scanResult.totalScore,
      maxScore: scanResult.maxScore,
      percentage: (scanResult.totalScore / scanResult.maxScore) * 100,
      correctCount: scanResult.answers.filter(a => a.isCorrect).length,
      incorrectCount: scanResult.answers.filter(a => !a.isCorrect).length,
      totalQuestions: scanResult.answers.length,
      examDate: exam.examDate,
    };

    await progress.addExamResult(scoreHistory);
  }
}

module.exports = new SubmissionService();
